api = "0.5"

[buildpack]
  homepage = "https://github.com/h2ik/buildpack-sidekiq"
  id = "h2ik/buildpack-sidekiq"
  name = "h2ik Sidekiq Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
